### ISSUE TITLE
Not quite an issue...

### ISSUE THREAD

**Issue by wanderrer** [TheIndra55/fivem-trams#2]
Hello there,
I have noticed that the tram sounds like the police horn on my server, is there a way to change that ?

**Comment by TheIndra55** [comment]
Probably the game using the same horn for the trams, I'm not sure where the horn sound is defined might be in the actual game binary as most train stuff is

**Comment by wanderrer** [comment]
yea, I will look into it, anyways it's a great resource, thank you for it :)
