### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by gaeVG** [TheIndra55/fivem-trams#6]
Hello, and thanks for sharing!

I have two small questions:
- Is this resource useful for the proper operation of the streetcars or is it more?
- If it is useful, how to use it? I have to take some courses node I half understand it : I tried an `npm install` or whatever, but nothing to do

Thanks in advance

**Comment by TheIndra55** [comment]
The node stuff in 'generator' is only to generate list of stations, not needed to run the resources.

**Comment by gaeVG** [comment]
[If only I read a little more](https://github.com/TheIndra55/fivem-trams/blob/master/scripts/nodes.js#L4) 😪
Thanks all the same
